import Head from 'next/head'
import Feed from '../components/Feed'
import Header from '../components/Header'
export default function Home() {
  return (
    <div>
      <Head>
        <title>IG-CLONE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/**header */}
      <Header/>

      {/**feed */}
      <Feed />

      {/**modal */}
    </div>
  )
}
