import Head from 'next/head'
import Feed from '../components/Feed'
import Header from '../components/Header'
import Modal from '../components/Modal'
import Profile from '../components/Profile'
import {auth} from '../firebase'
import { useAuthState } from 'react-firebase-hooks/auth'
import Login from '../components/Login'


export default function Home() {


  const [user] = useAuthState(auth)

  if(!user) return <Login/>

  return (
    <div className='bg-app'>
      <Head>
        <title>IG-CLONE</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>


      {/**header */}
      <Header user={user}/>

      {/**profile */}

     
     <Profile user={user} />
    

      {/**feed */}
      <Feed user={user} />

      {/**modal */}

      <Modal/>
    </div>
  )
}
